import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionaries
const translations = {
  en: {
    // Navbar
    events: 'Events',
    clubs: 'Clubs',
    myEvents: 'My Events',
    createEvent: 'Create Event',
    approvalPanel: 'Approval Panel',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    create: 'Create',
    approve: 'Approve',

    // Roles
    student: 'Student',
    club_manager: 'Club Manager',
    advisor: 'Advisor',
    admin: 'Admin',

    // Home Page
    campusEvents: 'Campus Events',
    allEvents: 'All Events',
    approved: 'Approved',
    pending: 'Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    noEventsFound: 'No events found',
    thereAreNoEvents: 'There are no events yet.',
    thereAreNoStatusEvents: 'There are no {status} events.',

    // Common labels
    date: 'Date',
    time: 'Time',
    location: 'Location',
    status: 'Status',
    reject: 'Reject',
    dateAndTime: 'Date & Time',
    capacityAndRegistrations: 'Capacity & Registrations',
    registered: 'registered',
    expected: 'Expected',

    // Approval Panel
    eventApprovalPanel: 'Event Approval Panel',
    reviewManageRequests: 'Review and manage event approval requests',
    pendingEvents: 'Pending Events',
    rejectedEvents: 'Rejected Events',
    noRejectedEvents: 'No rejected events',
    noEventsRejected: 'No events have been rejected.',
    noPendingEvents: 'No pending events',
    noEventsPending: 'All events have been reviewed.',
    rejectionInfo: 'Rejection Reason:',
    noReasonProvided: 'No reason provided',
    rejectedOn: 'Rejected on:',

    // My Events Page
    viewEventsYouRegistered: 'View all the events you have registered for',
    noRegistrationsYet: 'No registrations yet',
    startByBrowsingEvents: 'Start by browsing and registering for events',
    browseEvents: 'Browse Events',
    youAreRegisteredFor: 'You are registered for',
    event: 'event',

    // Notifications Page
    notifications: 'Notifications',
    manageYourNotifications: 'Manage and view all your notifications',
    all: 'All',
    unread: 'Unread',
    read: 'Read',
    markAllAsRead: 'Mark All as Read',
    deleteAllRead: 'Delete All Read',
    markAsRead: 'Mark as Read',
    delete: 'Delete',
    noNotificationsHere: 'No notifications here',
    noNotificationsYet: "You don't have any notifications yet",
    noUnreadNotifications: 'You have no unread notifications',
    noReadNotifications: 'You have no read notifications',
    failedToLoadNotifications: 'Failed to load notifications',
    markedAsRead: 'Marked as read',
    failedToMarkAsRead: 'Failed to mark as read',
    allNotificationsMarkedAsRead: 'All notifications marked as read',
    failedToMarkAllAsRead: 'Failed to mark all as read',
    notificationDeleted: 'Notification deleted',
    failedToDeleteNotification: 'Failed to delete notification',
    allReadNotificationsDeleted: 'All read notifications deleted',
    failedToDeleteNotifications: 'Failed to delete notifications',

    // Profile Page
    myProfile: 'My Profile',
    manageYourPersonalInfo: 'Manage your personal information and account settings',
    emailCannotBeChanged: 'Email address cannot be changed',
    enterStudentNumber: 'Enter your student number',
    department: 'Department',
    enterDepartment: 'Enter your department',
    role: 'Role',
    roleCannotBeChanged: 'Role is assigned by administrators',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdatedSuccessfully: 'Profile updated successfully!',
    failedToUpdateProfile: 'Failed to update profile',
    accountInformation: 'Account Information',
    memberSince: 'Member since',
    userId: 'User ID',

    // Auth
    signIn: 'Sign in',
    signInToAccount: 'Sign in to your account',
    emailAddress: 'Email address',
    password: 'Password',
    signingIn: 'Signing in...',
    dontHaveAccount: "Don't have an account? Register",

    // Password Reset
    forgotPassword: 'Forgot Password?',
    enterEmailForReset: 'Enter your email address to reset your password',
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    resetLinkSent: 'If the email exists, a reset link has been sent',
    checkYourEmail: 'Check Your Email',
    resetInstructions: 'If an account exists with this email, you will receive password reset instructions.',
    checkConsole: 'For demo purposes, check the backend console for the reset link.',
    backToLogin: 'Back to Login',
    resetPassword: 'Reset Password',
    enterNewPassword: 'Enter your new password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordResetSuccess: 'Password reset successful! Redirecting to login...',
    passwordResetFailed: 'Failed to reset password',
    invalidResetLink: 'Invalid or expired reset link',
    resetting: 'Resetting...',
    passwordRequirements: 'Password Requirements',
    minEightChars: 'At least 8 characters',
    oneUppercase: 'One uppercase letter',
    oneLowercase: 'One lowercase letter',
    oneNumber: 'One number',
    oneSpecialChar: 'One special character',

    // Register
    createAccount: 'Create your account',
    fullName: 'Full Name',
    studentNumber: 'Student Number (optional)',
    confirmPassword: 'Confirm Password',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account? Sign in',

    // EventCard
    viewDetails: 'View Details',
    viewEvent: 'View Event',
    capacity: 'Capacity',
    expected: 'Expected',
    attendees: 'attendees',
    room: 'Room',
    expectedAttendees: 'Expected Attendees',

    // EventDetail
    registerForEvent: 'Register for Event',
    unregister: 'Unregister',
    registering: 'Registering...',
    processing: 'Processing...',
    successfullyRegistered: 'Successfully registered for the event!',
    successfullyUnregistered: 'Successfully unregistered from the event',
    alreadyRegisteredError: 'You are already registered for this event',
    backToEvents: 'Back to Events',
    rejectionReason: 'Rejection Reason',
    eventUnrejected: 'Event moved back to pending',
    eventApproved: 'Event approved successfully!',
    enterRejectionReason: 'Enter rejection reason (optional):',
    returnToPending: 'Return to Pending',

    // ClubDetail
    follow: 'Follow',
    following: 'Following',
    loading: 'Loading...',
    nowFollowing: 'You are now following',
    unfollowed: 'You unfollowed',
    joinClub: 'Join Club',
    requestSent: 'Request Sent',
    joinRequestSent: 'Your join request has been sent',
    joinRequestCanceled: 'Join request canceled',
    member: 'Member',
    requestPending: 'Request Pending',
    requestToJoin: 'Request to Join',

    // Clubs Page
    campusClubs: 'Campus Clubs',
    exploreClubs: 'Explore all the clubs and organizations at Galatasaray University',
    noClubsFound: 'No clubs found',
    noClubsYet: 'There are no clubs registered yet.',
    members: 'members',
    followers: 'followers',
    allClubs: 'All Clubs',
    followedClubs: 'Followed Clubs',

    // ClubManagement
    clubManagement: 'Club Management',
    manageClubAndEvents: 'Manage your club and create events',
    joinRequests: 'Join Requests',
    noPendingRequests: 'No pending join requests',
    joinRequestApproved: 'Join request approved',
    joinRequestRejected: 'Join request rejected',
    failedToApproveRequest: 'Failed to approve join request',
    failedToRejectRequest: 'Failed to reject join request',
    noManagedClubs: 'You do not manage any clubs',
    failedToLoadJoinRequests: 'Failed to load join requests',
    createNewEvent: 'Create New Event',
    manage: 'Manage',
    noDescription: 'No description provided',
    noEventsYet: 'No events yet',

    // CreateEvent
    eventTitle: 'Event Title',
    description: 'Description',
    eventDate: 'Event Date & Time',
    expectedCapacity: 'Expected Capacity',
    expectedNumberOfParticipants: 'Expected Number of Participants',
    roomRecommendationsHelp: 'Room recommendations will appear below based on this capacity',
    recommendedRooms: 'Recommended Rooms',
    selectRoom: 'Select a room (optional)',
    selectClub: 'Select a club',
    location: 'Location',
    creating: 'Creating...',
    createEvent: 'Create Event',
    eventCreatedSuccess: 'Event created successfully!',
    enterEventTitle: 'Enter event title',
    enterEventDescription: 'Enter event description',
    dateAndTime: 'Date and Time',
    club: 'Club',
    maxCapacity: 'Maximum Capacity',
    enterExpectedCapacity: 'Enter expected capacity',
    enterMaxCapacity: 'Enter maximum capacity',
    theseRoomsRecommended: 'These rooms are recommended based on your expected capacity',
    enterLocation: 'Enter location (auto-filled if room selected)',
    imageUrl: 'Image URL (Optional)',
    membersOnly: 'Members Only',
    membersOnlyHelp: 'Only club members can register for this event',
    cancelEvent: 'Cancel Event',
    confirmCancelEvent: 'Are you sure you want to cancel this event? All registered users will be notified.',
    eventCancelled: 'Event cancelled successfully. All registered users have been notified.',
    eventCancelledNotice: 'Event Cancelled',
    youWereRegistered: 'You were registered for this event.',
    thisEventCancelled: 'This event has been cancelled.',

    // AdminPanel
    userManagement: 'User Management',
    manageAllUsers: 'Manage all users in the system. You can update roles and delete users.',
    filterByRole: 'Filter by Role',
    allRoles: 'All Roles',
    name: 'Name',
    email: 'Email',
    studentNumber: 'Student Number',
    department: 'Department',
    role: 'Role',
    actions: 'Actions',
    noUsersFound: 'No users found',
    you: '(You)',
    deleteUser: 'Delete user',
    cannotDeleteSelf: 'You cannot delete your own account',
    totalUsers: 'Total Users',
    areYouSureDelete: 'Are you sure you want to delete this user? This action cannot be undone.',
    failedToLoadUsers: 'Failed to load users',
    userRoleUpdated: 'User role updated successfully',
    failedToUpdateRole: 'Failed to update user role',
    userDeleted: 'User deleted successfully',
    failedToDeleteUser: 'Failed to delete user',

    // AdminClubManagement
    adminClubManagement: 'Club Management',
    createManageClubs: 'Create and manage all clubs in the system',
    createNewClub: 'Create New Club',
    editClub: 'Edit Club',
    clubName: 'Club Name',
    clubNameRequired: 'Club name is required',
    enterClubName: 'Enter club name',
    contactEmail: 'Contact Email',
    enterContactEmail: 'Enter contact email',
    selectManager: 'Select Manager (Optional)',
    selectAdvisor: 'Select Advisor (Optional)',
    logoUrl: 'Logo URL',
    enterLogoUrl: 'Enter logo URL',
    enterClubDescription: 'Enter club description',
    createClub: 'Create Club',
    updateClub: 'Update Club',
    clubCreatedSuccess: 'Club created successfully!',
    clubUpdatedSuccess: 'Club updated successfully!',
    failedToCreateClub: 'Failed to create club',
    failedToUpdateClub: 'Failed to update club',
    failedToDeleteClub: 'Failed to delete club',
    areYouSureDeleteClub: 'Are you sure you want to delete this club? This action cannot be undone.',
    clubDeleted: 'Club deleted successfully',
    notAssigned: 'Not assigned',
    failedToLoadData: 'Failed to load data',

    // ClubDetail
    clubManager: 'Club Manager',
    member: 'Member',
    requestToJoin: 'Request to Join',
    requestPending: 'Request Pending',
    joinRequestSent: 'Join request sent successfully',
    joinRequestCanceled: 'Join request canceled',
    follow: 'Follow',
    following: 'Following',
    nowFollowing: 'Now following',
    unfollowed: 'Unfollowed',
    loading: 'Loading...',
    clubEvents: 'Club Events',
    clubMembers: 'Club Members',
    noMembersYet: 'No members yet',
    removeMember: 'Remove Member',
    confirmRemoveMember: 'Are you sure you want to remove this member from the club?',
    memberRemoved: 'Member removed successfully',
    failedToRemoveMember: 'Failed to remove member',
    editDescription: 'Edit Description',
    updateDescription: 'Update Description',
    descriptionUpdated: 'Description updated successfully',
    failedToUpdateDescription: 'Failed to update description',
    enterRejectionReason: 'Enter rejection reason (optional)',
    capacity: 'Capacity',

    // General
    submit: 'Submit',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    adminPanel: 'Admin Panel',

    // Pagination
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    total: 'total',
  },

  tr: {
    // Navbar
    events: 'Etkinlikler',
    clubs: 'Kulüpler',
    myEvents: 'Etkinliklerim',
    createEvent: 'Etkinlik Oluştur',
    approvalPanel: 'Onay Paneli',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    create: 'Oluştur',
    approve: 'Onayla',

    // Roles
    student: 'Öğrenci',
    club_manager: 'Kulüp Yöneticisi',
    advisor: 'Danışman',
    admin: 'Yönetici',

    // Home Page
    campusEvents: 'Kampüs Etkinlikleri',
    allEvents: 'Tüm Etkinlikler',
    approved: 'Onaylandı',
    pending: 'Beklemede',
    completed: 'Tamamlandı',
    rejected: 'Reddedildi',
    cancelled: 'İptal Edildi',
    noEventsFound: 'Etkinlik bulunamadı',
    thereAreNoEvents: 'Henüz etkinlik yok.',
    thereAreNoStatusEvents: '{status} etkinlik yok.',

    // Common labels
    date: 'Tarih',
    time: 'Saat',
    location: 'Konum',
    status: 'Durum',
    reject: 'Reddet',
    dateAndTime: 'Tarih ve Saat',
    capacityAndRegistrations: 'Kapasite ve Kayıtlar',
    registered: 'kayıtlı',
    expected: 'Beklenen',

    // Approval Panel
    eventApprovalPanel: 'Etkinlik Onay Paneli',
    reviewManageRequests: 'Etkinlik onay taleplerini inceleyin ve yönetin',
    pendingEvents: 'Bekleyen Etkinlikler',
    rejectedEvents: 'Reddedilen Etkinlikler',
    noRejectedEvents: 'Reddedilen etkinlik yok',
    noEventsRejected: 'Henüz reddedilen etkinlik bulunmuyor.',
    noPendingEvents: 'Bekleyen etkinlik yok',
    noEventsPending: 'Tüm etkinlikler incelendi.',
    rejectionInfo: 'Ret Nedeni:',
    noReasonProvided: 'Neden belirtilmedi',
    rejectedOn: 'Reddedilme tarihi:',

    // My Events Page
    viewEventsYouRegistered: 'Kayıt olduğunuz tüm etkinlikleri görüntüleyin',
    noRegistrationsYet: 'Henüz kayıt yok',
    startByBrowsingEvents: 'Etkinliklere göz atarak ve kayıt olarak başlayın',
    browseEvents: 'Etkinliklere Göz At',
    youAreRegisteredFor: 'Kayıtlı olduğunuz etkinlik sayısı',
    event: 'etkinlik',

    // Notifications Page
    notifications: 'Bildirimler',
    manageYourNotifications: 'Tüm bildirimlerinizi görüntüleyin ve yönetin',
    all: 'Tümü',
    unread: 'Okunmamış',
    read: 'Okunmuş',
    markAllAsRead: 'Tümünü Okundu Olarak İşaretle',
    deleteAllRead: 'Tüm Okunmuşları Sil',
    markAsRead: 'Okundu Olarak İşaretle',
    delete: 'Sil',
    noNotificationsHere: 'Burada bildirim yok',
    noNotificationsYet: 'Henüz hiç bildiriminiz yok',
    noUnreadNotifications: 'Okunmamış bildiriminiz yok',
    noReadNotifications: 'Okunmuş bildiriminiz yok',
    failedToLoadNotifications: 'Bildirimler yüklenemedi',
    markedAsRead: 'Okundu olarak işaretlendi',
    failedToMarkAsRead: 'Okundu olarak işaretlenemedi',
    allNotificationsMarkedAsRead: 'Tüm bildirimler okundu olarak işaretlendi',
    failedToMarkAllAsRead: 'Tüm bildirimler okundu olarak işaretlenemedi',
    notificationDeleted: 'Bildirim silindi',
    failedToDeleteNotification: 'Bildirim silinemedi',
    allReadNotificationsDeleted: 'Tüm okunmuş bildirimler silindi',
    failedToDeleteNotifications: 'Bildirimler silinemedi',

    // Profile Page
    myProfile: 'Profilim',
    manageYourPersonalInfo: 'Kişisel bilgilerinizi ve hesap ayarlarınızı yönetin',
    emailCannotBeChanged: 'E-posta adresi değiştirilemez',
    enterStudentNumber: 'Öğrenci numaranızı girin',
    department: 'Bölüm',
    enterDepartment: 'Bölümünüzü girin',
    role: 'Rol',
    roleCannotBeChanged: 'Rol yöneticiler tarafından atanır',
    saveChanges: 'Değişiklikleri Kaydet',
    saving: 'Kaydediliyor...',
    profileUpdatedSuccessfully: 'Profil başarıyla güncellendi!',
    failedToUpdateProfile: 'Profil güncellenemedi',
    accountInformation: 'Hesap Bilgileri',
    memberSince: 'Üyelik tarihi',
    userId: 'Kullanıcı ID',

    // Auth
    signIn: 'Giriş Yap',
    signInToAccount: 'Hesabınıza giriş yapın',
    emailAddress: 'E-posta adresi',
    password: 'Şifre',
    signingIn: 'Giriş yapılıyor...',
    dontHaveAccount: 'Hesabınız yok mu? Kayıt olun',

    // Password Reset
    forgotPassword: 'Şifrenizi mi unuttunuz?',
    enterEmailForReset: 'Şifrenizi sıfırlamak için e-posta adresinizi girin',
    sendResetLink: 'Sıfırlama Bağlantısı Gönder',
    sending: 'Gönderiliyor...',
    resetLinkSent: 'E-posta mevcutsa, sıfırlama bağlantısı gönderildi',
    checkYourEmail: 'E-postanızı Kontrol Edin',
    resetInstructions: 'Bu e-posta ile bir hesap varsa, şifre sıfırlama talimatlarını alacaksınız.',
    checkConsole: 'Demo amaçlı, sıfırlama bağlantısı için backend konsolunu kontrol edin.',
    backToLogin: 'Girişe Dön',
    resetPassword: 'Şifreyi Sıfırla',
    enterNewPassword: 'Yeni şifrenizi girin',
    newPassword: 'Yeni Şifre',
    confirmNewPassword: 'Yeni Şifreyi Onayla',
    passwordsDoNotMatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre en az 8 karakter olmalıdır',
    passwordResetSuccess: 'Şifre başarıyla sıfırlandı! Giriş sayfasına yönlendiriliyorsunuz...',
    passwordResetFailed: 'Şifre sıfırlama başarısız',
    invalidResetLink: 'Geçersiz veya süresi dolmuş sıfırlama bağlantısı',
    resetting: 'Sıfırlanıyor...',
    passwordRequirements: 'Şifre Gereksinimleri',
    minEightChars: 'En az 8 karakter',
    oneUppercase: 'Bir büyük harf',
    oneLowercase: 'Bir küçük harf',
    oneNumber: 'Bir sayı',
    oneSpecialChar: 'Bir özel karakter',

    // Register
    createAccount: 'Hesap oluştur',
    fullName: 'Ad Soyad',
    studentNumber: 'Öğrenci Numarası (opsiyonel)',
    confirmPassword: 'Şifreyi Onayla',
    creatingAccount: 'Hesap oluşturuluyor...',
    alreadyHaveAccount: 'Zaten hesabınız var mı? Giriş yapın',

    // EventCard
    viewDetails: 'Detayları Gör',
    viewEvent: 'Etkinliği Görüntüle',
    capacity: 'Kapasite',
    expected: 'Beklenen',
    attendees: 'katılımcı',
    room: 'Oda',
    expectedAttendees: 'Beklenen Katılımcı',

    // EventDetail
    registerForEvent: 'Etkinliğe Kayıt Ol',
    unregister: 'Kaydı İptal Et',
    registering: 'Kayıt Olunuyor...',
    processing: 'İşleniyor...',
    successfullyRegistered: 'Etkinliğe başarıyla kayıt oldunuz!',
    successfullyUnregistered: 'Etkinlik kaydınız başarıyla iptal edildi',
    alreadyRegisteredError: 'Bu etkinliğe zaten kayıtlısınız',
    backToEvents: 'Etkinliklere Dön',
    rejectionReason: 'Red Nedeni',
    eventUnrejected: 'Etkinlik tekrar beklemede durumuna alındı',
    eventApproved: 'Etkinlik başarıyla onaylandı!',
    enterRejectionReason: 'Red nedenini girin (opsiyonel):',
    returnToPending: 'Bekleyenler\'e Geri Al',

    // ClubDetail
    follow: 'Takip Et',
    following: 'Takip Ediliyor',
    loading: 'Yükleniyor...',
    nowFollowing: 'Artık takip ediyorsunuz:',
    unfollowed: 'Takibi bıraktınız:',
    joinClub: 'Kulübe Katıl',
    requestSent: 'İstek Gönderildi',
    joinRequestSent: 'Katılma isteğiniz gönderildi',
    joinRequestCanceled: 'Katılma isteği iptal edildi',
    member: 'Üye',
    requestPending: 'İstek Beklemede',
    requestToJoin: 'Katılma İsteği Gönder',

    // Clubs Page
    campusClubs: 'Kampüs Kulüpleri',
    exploreClubs: 'Galatasaray Üniversitesi\'ndeki tüm kulüpleri ve organizasyonları keşfedin',
    noClubsFound: 'Kulüp bulunamadı',
    noClubsYet: 'Henüz kayıtlı kulüp yok.',
    members: 'üye',
    followers: 'takipçi',
    allClubs: 'Tüm Kulüpler',
    followedClubs: 'Takip Edilen Kulüpler',

    // ClubManagement
    clubManagement: 'Kulüp Yönetimi',
    manageClubAndEvents: 'Kulübünüzü yönetin ve etkinlik oluşturun',
    joinRequests: 'Katılma İstekleri',
    noPendingRequests: 'Bekleyen katılma isteği yok',
    joinRequestApproved: 'Katılma isteği onaylandı',
    joinRequestRejected: 'Katılma isteği reddedildi',
    failedToApproveRequest: 'Katılma isteği onaylanamadı',
    failedToRejectRequest: 'Katılma isteği reddedilemedi',
    noManagedClubs: 'Yönettiğiniz bir kulüp bulunmuyor',
    failedToLoadJoinRequests: 'Katılma istekleri yüklenemedi',
    createNewEvent: 'Yeni Etkinlik Oluştur',
    manage: 'Yönet',
    noDescription: 'Açıklama eklenmemiş',
    noEventsYet: 'Henüz etkinlik yok',

    // CreateEvent
    eventTitle: 'Etkinlik Başlığı',
    description: 'Açıklama',
    eventDate: 'Etkinlik Tarihi ve Saati',
    expectedCapacity: 'Tahmini Katılımcı Sayısı',
    expectedNumberOfParticipants: 'Beklenen Katılımcı Sayısı',
    roomRecommendationsHelp: 'Bu kapasiteye göre oda önerileri aşağıda görünecektir',
    recommendedRooms: 'Önerilen Odalar',
    selectRoom: 'Bir oda seçin (opsiyonel)',
    selectClub: 'Bir kulüp seçin',
    location: 'Konum',
    creating: 'Oluşturuluyor...',
    createEvent: 'Etkinlik Oluştur',
    eventCreatedSuccess: 'Etkinlik başarıyla oluşturuldu!',
    enterEventTitle: 'Etkinlik başlığını girin',
    enterEventDescription: 'Etkinlik açıklamasını girin',
    dateAndTime: 'Tarih ve Saat',
    club: 'Kulüp',
    maxCapacity: 'Maksimum Kapasite',
    enterExpectedCapacity: 'Beklenen kapasiteyi girin',
    enterMaxCapacity: 'Maksimum kapasiteyi girin',
    theseRoomsRecommended: 'Bu odalar beklenen kapasitenize göre önerilmektedir',
    enterLocation: 'Konumu girin (oda seçilirse otomatik doldurulur)',
    imageUrl: 'Görsel URL (Opsiyonel)',
    membersOnly: 'Sadece Üyeler',
    membersOnlyHelp: 'Sadece kulüp üyeleri bu etkinliğe kayıt olabilir',
    cancelEvent: 'Etkinliği İptal Et',
    confirmCancelEvent: 'Bu etkinliği iptal etmek istediğinizden emin misiniz? Tüm kayıtlı kullanıcılar bilgilendirilecektir.',
    eventCancelled: 'Etkinlik başarıyla iptal edildi. Tüm kayıtlı kullanıcılar bilgilendirildi.',
    eventCancelledNotice: 'Etkinlik İptal Edildi',
    youWereRegistered: 'Bu etkinliğe kayıtlıydınız.',
    thisEventCancelled: 'Bu etkinlik iptal edildi.',

    // AdminPanel
    userManagement: 'Kullanıcı Yönetimi',
    manageAllUsers: 'Sistemdeki tüm kullanıcıları yönetin. Rolleri güncelleyebilir ve kullanıcıları silebilirsiniz.',
    filterByRole: 'Role Göre Filtrele',
    allRoles: 'Tüm Roller',
    name: 'İsim',
    email: 'E-posta',
    studentNumber: 'Öğrenci Numarası',
    department: 'Bölüm',
    role: 'Rol',
    actions: 'İşlemler',
    noUsersFound: 'Kullanıcı bulunamadı',
    you: '(Siz)',
    deleteUser: 'Kullanıcıyı sil',
    cannotDeleteSelf: 'Kendi hesabınızı silemezsiniz',
    totalUsers: 'Toplam Kullanıcı',
    areYouSureDelete: 'Bu kullanıcıyı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    failedToLoadUsers: 'Kullanıcılar yüklenemedi',
    userRoleUpdated: 'Kullanıcı rolü başarıyla güncellendi',
    failedToUpdateRole: 'Kullanıcı rolü güncellenemedi',
    userDeleted: 'Kullanıcı başarıyla silindi',
    failedToDeleteUser: 'Kullanıcı silinemedi',

    // AdminClubManagement
    adminClubManagement: 'Kulüp Yönetimi',
    createManageClubs: 'Sistemdeki tüm kulüpleri oluşturun ve yönetin',
    createNewClub: 'Yeni Kulüp Oluştur',
    editClub: 'Kulübü Düzenle',
    clubName: 'Kulüp Adı',
    clubNameRequired: 'Kulüp adı gereklidir',
    enterClubName: 'Kulüp adını girin',
    contactEmail: 'İletişim E-postası',
    enterContactEmail: 'İletişim e-postasını girin',
    selectManager: 'Yönetici Seç (Opsiyonel)',
    selectAdvisor: 'Danışman Seç (Opsiyonel)',
    logoUrl: 'Logo URL',
    enterLogoUrl: 'Logo URL girin',
    enterClubDescription: 'Kulüp açıklamasını girin',
    createClub: 'Kulüp Oluştur',
    updateClub: 'Kulübü Güncelle',
    clubCreatedSuccess: 'Kulüp başarıyla oluşturuldu!',
    clubUpdatedSuccess: 'Kulüp başarıyla güncellendi!',
    failedToCreateClub: 'Kulüp oluşturulamadı',
    failedToUpdateClub: 'Kulüp güncellenemedi',
    failedToDeleteClub: 'Kulüp silinemedi',
    areYouSureDeleteClub: 'Bu kulübü silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    clubDeleted: 'Kulüp başarıyla silindi',
    notAssigned: 'Atanmadı',
    failedToLoadData: 'Veri yüklenemedi',

    // ClubDetail
    clubManager: 'Kulüp Yöneticisi',
    member: 'Üye',
    requestToJoin: 'Katılma İsteği Gönder',
    requestPending: 'İstek Beklemede',
    joinRequestSent: 'Katılma isteği başarıyla gönderildi',
    joinRequestCanceled: 'Katılma isteği iptal edildi',
    follow: 'Takip Et',
    following: 'Takip Ediliyor',
    nowFollowing: 'Artık takip ediyorsunuz',
    unfollowed: 'Takip bırakıldı',
    loading: 'Yükleniyor...',
    clubEvents: 'Kulüp Etkinlikleri',
    clubMembers: 'Kulüp Üyeleri',
    noMembersYet: 'Henüz üye yok',
    removeMember: 'Üyelikten Çıkar',
    confirmRemoveMember: 'Bu üyeyi kulüpten çıkarmak istediğinizden emin misiniz?',
    memberRemoved: 'Üye başarıyla çıkarıldı',
    failedToRemoveMember: 'Üye çıkarılamadı',
    editDescription: 'Açıklamayı Düzenle',
    updateDescription: 'Açıklamayı Güncelle',
    descriptionUpdated: 'Açıklama başarıyla güncellendi',
    failedToUpdateDescription: 'Açıklama güncellenemedi',
    enterRejectionReason: 'Ret sebebini girin (opsiyonel)',
    capacity: 'Kapasite',

    // General
    submit: 'Gönder',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    save: 'Kaydet',
    adminPanel: 'Yönetici Paneli',

    // Pagination
    previous: 'Önceki',
    next: 'Sonraki',
    page: 'Sayfa',
    of: '/',
    total: 'toplam',
  },

  fr: {
    // Navbar
    events: 'Événements',
    clubs: 'Clubs',
    myEvents: 'Mes événements',
    createEvent: 'Créer un événement',
    approvalPanel: "Panneau d'approbation",
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    create: 'Créer',
    approve: 'Approuver',

    // Roles
    student: 'Étudiant',
    club_manager: 'Gestionnaire de club',
    advisor: 'Conseiller',
    admin: 'Administrateur',

    // Home Page
    campusEvents: 'Événements du campus',
    allEvents: 'Tous les événements',
    approved: 'Approuvé',
    pending: 'En attente',
    completed: 'Terminé',
    rejected: 'Rejeté',
    cancelled: 'Annulé',
    noEventsFound: 'Aucun événement trouvé',
    thereAreNoEvents: "Il n'y a pas encore d'événements.",
    thereAreNoStatusEvents: "Il n'y a pas d'événements {status}.",

    // Common labels
    date: 'Date',
    time: 'Heure',
    location: 'Lieu',
    status: 'Statut',
    reject: 'Rejeter',
    dateAndTime: 'Date et heure',
    capacityAndRegistrations: 'Capacité et inscriptions',
    registered: 'inscrits',
    expected: 'Attendu',

    // Approval Panel
    eventApprovalPanel: "Panneau d'approbation des événements",
    reviewManageRequests: "Examiner et gérer les demandes d'approbation d'événements",
    pendingEvents: 'Événements en attente',
    rejectedEvents: 'Événements rejetés',
    noRejectedEvents: 'Aucun événement rejeté',
    noEventsRejected: "Aucun événement n'a été rejeté.",
    noPendingEvents: 'Aucun événement en attente',
    noEventsPending: 'Tous les événements ont été examinés.',
    rejectionInfo: 'Raison du rejet:',
    noReasonProvided: 'Aucune raison fournie',
    rejectedOn: 'Rejeté le:',

    // My Events Page
    viewEventsYouRegistered: 'Voir tous les événements auxquels vous êtes inscrit',
    noRegistrationsYet: 'Aucune inscription pour le moment',
    startByBrowsingEvents: "Commencez par parcourir et vous inscrire aux événements",
    browseEvents: 'Parcourir les événements',
    youAreRegisteredFor: 'Vous êtes inscrit à',
    event: 'événement',

    // Notifications Page
    notifications: 'Notifications',
    manageYourNotifications: 'Gérer et voir toutes vos notifications',
    all: 'Tout',
    unread: 'Non lu',
    read: 'Lu',
    markAllAsRead: 'Tout marquer comme lu',
    deleteAllRead: 'Supprimer tout ce qui est lu',
    markAsRead: 'Marquer comme lu',
    delete: 'Supprimer',
    noNotificationsHere: 'Aucune notification ici',
    noNotificationsYet: "Vous n'avez pas encore de notifications",
    noUnreadNotifications: "Vous n'avez aucune notification non lue",
    noReadNotifications: "Vous n'avez aucune notification lue",
    failedToLoadNotifications: 'Échec du chargement des notifications',
    markedAsRead: 'Marqué comme lu',
    failedToMarkAsRead: 'Échec du marquage comme lu',
    allNotificationsMarkedAsRead: 'Toutes les notifications marquées comme lues',
    failedToMarkAllAsRead: 'Échec du marquage de toutes comme lues',
    notificationDeleted: 'Notification supprimée',
    failedToDeleteNotification: 'Échec de la suppression de la notification',
    allReadNotificationsDeleted: 'Toutes les notifications lues supprimées',
    failedToDeleteNotifications: 'Échec de la suppression des notifications',

    // Profile Page
    myProfile: 'Mon profil',
    manageYourPersonalInfo: 'Gérer vos informations personnelles et paramètres de compte',
    emailCannotBeChanged: "L'adresse e-mail ne peut pas être modifiée",
    enterStudentNumber: 'Entrez votre numéro étudiant',
    department: 'Département',
    enterDepartment: 'Entrez votre département',
    role: 'Rôle',
    roleCannotBeChanged: 'Le rôle est attribué par les administrateurs',
    saveChanges: 'Enregistrer les modifications',
    saving: 'Enregistrement...',
    profileUpdatedSuccessfully: 'Profil mis à jour avec succès!',
    failedToUpdateProfile: 'Échec de la mise à jour du profil',
    accountInformation: 'Informations du compte',
    memberSince: 'Membre depuis',
    userId: 'ID utilisateur',

    // Auth
    signIn: 'Se connecter',
    signInToAccount: 'Connectez-vous à votre compte',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    signingIn: 'Connexion en cours...',
    dontHaveAccount: "Vous n'avez pas de compte? S'inscrire",

    // Password Reset
    forgotPassword: 'Mot de passe oublié?',
    enterEmailForReset: 'Entrez votre adresse e-mail pour réinitialiser votre mot de passe',
    sendResetLink: 'Envoyer le lien de réinitialisation',
    sending: 'Envoi...',
    resetLinkSent: "Si l'e-mail existe, un lien de réinitialisation a été envoyé",
    checkYourEmail: 'Vérifiez votre e-mail',
    resetInstructions: "Si un compte existe avec cet e-mail, vous recevrez des instructions de réinitialisation de mot de passe.",
    checkConsole: 'À des fins de démonstration, vérifiez la console backend pour le lien de réinitialisation.',
    backToLogin: 'Retour à la connexion',
    resetPassword: 'Réinitialiser le mot de passe',
    enterNewPassword: 'Entrez votre nouveau mot de passe',
    newPassword: 'Nouveau mot de passe',
    confirmNewPassword: 'Confirmer le nouveau mot de passe',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Le mot de passe doit contenir au moins 8 caractères',
    passwordResetSuccess: 'Réinitialisation du mot de passe réussie! Redirection vers la connexion...',
    passwordResetFailed: 'Échec de la réinitialisation du mot de passe',
    invalidResetLink: 'Lien de réinitialisation invalide ou expiré',
    resetting: 'Réinitialisation...',
    passwordRequirements: 'Exigences du mot de passe',
    minEightChars: 'Au moins 8 caractères',
    oneUppercase: 'Une lettre majuscule',
    oneLowercase: 'Une lettre minuscule',
    oneNumber: 'Un chiffre',
    oneSpecialChar: 'Un caractère spécial',

    // Register
    createAccount: 'Créer votre compte',
    fullName: 'Nom complet',
    studentNumber: "Numéro d'étudiant (optionnel)",
    confirmPassword: 'Confirmer le mot de passe',
    creatingAccount: 'Création du compte...',
    alreadyHaveAccount: 'Vous avez déjà un compte? Se connecter',

    // EventCard
    viewDetails: 'Voir les détails',
    viewEvent: 'Voir l\'événement',
    capacity: 'Capacité',
    expected: 'Attendu',
    attendees: 'participants',
    room: 'Salle',
    expectedAttendees: 'Participants attendus',

    // EventDetail
    registerForEvent: "S'inscrire à l'événement",
    unregister: 'Se désinscrire',
    registering: 'Inscription en cours...',
    processing: 'Traitement...',
    successfullyRegistered: "Vous êtes inscrit à l'événement avec succès!",
    successfullyUnregistered: "Vous êtes désinscrit de l'événement",
    alreadyRegisteredError: 'Vous êtes déjà inscrit à cet événement',
    backToEvents: 'Retour aux événements',
    rejectionReason: 'Raison du rejet',
    eventUnrejected: "L'événement est de nouveau en attente",
    eventApproved: "Événement approuvé avec succès!",
    enterRejectionReason: 'Entrez la raison du rejet (optionnel):',
    returnToPending: 'Retourner en attente',

    // ClubDetail
    follow: 'Suivre',
    following: 'Suivi',
    loading: 'Chargement...',
    nowFollowing: 'Vous suivez maintenant',
    unfollowed: 'Vous ne suivez plus',
    joinClub: 'Rejoindre le club',
    requestSent: 'Demande envoyée',
    joinRequestSent: 'Votre demande d\'adhésion a été envoyée',
    joinRequestCanceled: 'Demande d\'adhésion annulée',
    member: 'Membre',
    requestPending: 'Demande en attente',
    requestToJoin: 'Demander à rejoindre',

    // Clubs Page
    campusClubs: 'Clubs du campus',
    exploreClubs: "Explorez tous les clubs et organisations de l'Université Galatasaray",
    noClubsFound: 'Aucun club trouvé',
    noClubsYet: "Il n'y a pas encore de clubs enregistrés.",
    members: 'membres',
    followers: 'abonnés',
    allClubs: 'Tous les clubs',
    followedClubs: 'Clubs suivis',

    // ClubManagement
    clubManagement: 'Gestion du club',
    manageClubAndEvents: 'Gérez votre club et créez des événements',
    joinRequests: "Demandes d'adhésion",
    noPendingRequests: "Aucune demande d'adhésion en attente",
    joinRequestApproved: "Demande d'adhésion approuvée",
    joinRequestRejected: "Demande d'adhésion rejetée",
    failedToApproveRequest: "Échec de l'approbation de la demande d'adhésion",
    failedToRejectRequest: "Échec du rejet de la demande d'adhésion",
    noManagedClubs: 'Vous ne gérez aucun club',
    failedToLoadJoinRequests: "Échec du chargement des demandes d'adhésion",
    createNewEvent: 'Créer un nouvel événement',
    manage: 'Gérer',
    noDescription: 'Aucune description fournie',
    noEventsYet: 'Pas encore d\'événements',

    // CreateEvent
    eventTitle: "Titre de l'événement",
    description: 'Description',
    eventDate: "Date et heure de l'événement",
    expectedCapacity: 'Capacité attendue',
    expectedNumberOfParticipants: 'Nombre de participants attendus',
    roomRecommendationsHelp: 'Les recommandations de salle apparaîtront ci-dessous en fonction de cette capacité',
    recommendedRooms: 'Salles recommandées',
    selectRoom: 'Sélectionner une salle (optionnel)',
    selectClub: 'Sélectionner un club',
    location: 'Emplacement',
    creating: 'Création...',
    createEvent: 'Créer un événement',
    eventCreatedSuccess: 'Événement créé avec succès!',
    enterEventTitle: "Entrez le titre de l'événement",
    enterEventDescription: "Entrez la description de l'événement",
    dateAndTime: 'Date et heure',
    club: 'Club',
    maxCapacity: 'Capacité maximale',
    enterExpectedCapacity: 'Entrez la capacité attendue',
    enterMaxCapacity: 'Entrez la capacité maximale',
    theseRoomsRecommended: 'Ces salles sont recommandées en fonction de votre capacité attendue',
    enterLocation: 'Entrez l\'emplacement (auto-rempli si une salle est sélectionnée)',
    imageUrl: 'URL de l\'image (Optionnel)',
    membersOnly: 'Membres uniquement',
    membersOnlyHelp: 'Seuls les membres du club peuvent s\'inscrire à cet événement',
    cancelEvent: 'Annuler l\'événement',
    confirmCancelEvent: 'Êtes-vous sûr de vouloir annuler cet événement ? Tous les utilisateurs inscrits seront notifiés.',
    eventCancelled: 'Événement annulé avec succès. Tous les utilisateurs inscrits ont été notifiés.',
    eventCancelledNotice: 'Événement annulé',
    youWereRegistered: 'Vous étiez inscrit à cet événement.',
    thisEventCancelled: 'Cet événement a été annulé.',

    // AdminPanel
    userManagement: 'Gestion des utilisateurs',
    manageAllUsers: 'Gérez tous les utilisateurs du système. Vous pouvez mettre à jour les rôles et supprimer les utilisateurs.',
    filterByRole: 'Filtrer par rôle',
    allRoles: 'Tous les rôles',
    name: 'Nom',
    email: 'E-mail',
    studentNumber: 'Numéro d\'étudiant',
    department: 'Département',
    role: 'Rôle',
    actions: 'Actions',
    noUsersFound: 'Aucun utilisateur trouvé',
    you: '(Vous)',
    deleteUser: 'Supprimer l\'utilisateur',
    cannotDeleteSelf: 'Vous ne pouvez pas supprimer votre propre compte',
    totalUsers: 'Total des utilisateurs',
    areYouSureDelete: 'Êtes-vous sûr de vouloir supprimer cet utilisateur? Cette action ne peut pas être annulée.',
    failedToLoadUsers: 'Échec du chargement des utilisateurs',
    userRoleUpdated: 'Rôle de l\'utilisateur mis à jour avec succès',
    failedToUpdateRole: 'Échec de la mise à jour du rôle de l\'utilisateur',
    userDeleted: 'Utilisateur supprimé avec succès',
    failedToDeleteUser: 'Échec de la suppression de l\'utilisateur',

    // AdminClubManagement
    adminClubManagement: 'Gestion des clubs',
    createManageClubs: 'Créer et gérer tous les clubs du système',
    createNewClub: 'Créer un nouveau club',
    editClub: 'Modifier le club',
    clubName: 'Nom du club',
    clubNameRequired: 'Le nom du club est requis',
    enterClubName: 'Entrez le nom du club',
    contactEmail: 'E-mail de contact',
    enterContactEmail: 'Entrez l\'e-mail de contact',
    selectManager: 'Sélectionner un gestionnaire (Optionnel)',
    selectAdvisor: 'Sélectionner un conseiller (Optionnel)',
    logoUrl: 'URL du logo',
    enterLogoUrl: 'Entrez l\'URL du logo',
    enterClubDescription: 'Entrez la description du club',
    createClub: 'Créer le club',
    updateClub: 'Mettre à jour le club',
    clubCreatedSuccess: 'Club créé avec succès!',
    clubUpdatedSuccess: 'Club mis à jour avec succès!',
    failedToCreateClub: 'Échec de la création du club',
    failedToUpdateClub: 'Échec de la mise à jour du club',
    failedToDeleteClub: 'Échec de la suppression du club',
    areYouSureDeleteClub: 'Êtes-vous sûr de vouloir supprimer ce club? Cette action ne peut pas être annulée.',
    clubDeleted: 'Club supprimé avec succès',
    notAssigned: 'Non attribué',
    failedToLoadData: 'Échec du chargement des données',

    // ClubDetail
    clubManager: 'Gestionnaire du club',
    member: 'Membre',
    requestToJoin: 'Demander à rejoindre',
    requestPending: 'Demande en attente',
    joinRequestSent: 'Demande d\'adhésion envoyée avec succès',
    joinRequestCanceled: 'Demande d\'adhésion annulée',
    follow: 'Suivre',
    following: 'Suivi',
    nowFollowing: 'Vous suivez maintenant',
    unfollowed: 'Ne plus suivre',
    loading: 'Chargement...',
    clubEvents: 'Événements du club',
    clubMembers: 'Membres du club',
    noMembersYet: 'Pas encore de membres',
    removeMember: 'Retirer le membre',
    confirmRemoveMember: 'Êtes-vous sûr de vouloir retirer ce membre du club?',
    memberRemoved: 'Membre retiré avec succès',
    failedToRemoveMember: 'Échec du retrait du membre',
    editDescription: 'Modifier la description',
    updateDescription: 'Mettre à jour la description',
    descriptionUpdated: 'Description mise à jour avec succès',
    failedToUpdateDescription: 'Échec de la mise à jour de la description',
    enterRejectionReason: 'Entrez la raison du refus (optionnel)',
    capacity: 'Capacité',

    // General
    submit: 'Soumettre',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Sauvegarder',
    adminPanel: "Panneau d'administration",

    // Pagination
    previous: 'Précédent',
    next: 'Suivant',
    page: 'Page',
    of: 'sur',
    total: 'au total',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to Turkish
    return localStorage.getItem('language') || 'tr';
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  const value = {
    language,
    changeLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
